[pytest]
pythonpath = .

testpaths =
    tests

python_files =
    test_*.py

python_classes =
    Test*

python_functions =
    test_*

markers =
    unit: Fast unit tests
    integration: Integration tests
    e2e: E2E tests

addopts =
    -ra
    --strict-markers
    --cov=src
    --cov-report=term-missing