[pytest]
pythonpath = .

testpaths =
    tests

python_files =
    test_*.py

python_classes =
    Test*

python_functions =
    test_*

markers =
    unit: Fast unit tests
    integration: Integration tests
    E2E: E2E tests

addopts =
    -ra
    --strict-markers